Update OpenCLNet.dll HintPath
- Use $(Configuration) instead of Release in path
- Update from net40 to net47
- Fixes:
Error CS0246 The type or namespace name 'OpenCLNet' could not be found
(are you missing a using directive or an assembly reference?)
CUETools.FLACL.cmd cuetools.net\CUETools.FLACCL.cmd\Program.cs 359 N/A